# Generated by Django 4.2.10 on 2024-03-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=100)),
                ('Date', models.DateField(blank=True, verbose_name='Conversation Date')),
                ('Time', models.TimeField(blank=True, verbose_name='Conversation Time')),
            ],
        ),
    ]
